### ISSUE TITLE
UNAUTHORIZED error getting tags of repository

### ISSUE THREAD

**Issue by ccalvarez** [al4/docker-registry-list#2]
Hi.

I can obtain the list of tags for the alpine repository:

![image](https://user-images.githubusercontent.com/2665104/84523625-d90f8900-ac95-11ea-8a17-c2455b9ea183.png)

But when I try to get the tags for the [hasura/graphql-engine](https://hub.docker.com/r/hasura/graphql-engine) repository I get this error:

![image](https://user-images.githubusercontent.com/2665104/84523746-1bd16100-ac96-11ea-9abc-9cf09ed195fb.png)

I'm on Windows 10 Pro Version 1709, running Python 3.8.1.

Thank you.

**Comment by al4** [comment]
It appears that this repository doesn't allow anonymous tokens to list the tags. I'm not sure why they would do this, but if you want permission you'll need to contact the owner of the repository.

I had a quick play to see if it needed you to paginate with a large number of tags, or use a signed in docker hub account, but both of those still show unauthorized.
